### ISSUE TITLE
All discovery tests block/timeout on Ubuntu 15.10

### ISSUE THREAD

**Issue by tomviner** [tjguk/networkzero#12]
Testing against Python 2.7, 3.4 & 3.5, all the tests in test_discovery.py just blocked until I killed them. So I added [pytest-timeout](https://pypi.python.org/pypi/pytest-timeout), with [this diff](https://github.com/tomviner/networkzero/pull/1/files), to fail tests that take longer than 10 seconds..

[Full test output here](https://gist.github.com/tomviner/2e954786dc241ca505410b76ff277ed2), against those 3 python version.

Possibly related to https://github.com/tjguk/networkzero/issues/7 *Discovery works poorly when synchronous with advertising*

**Comment by tjguk** [comment]
Thanks for that, Tom. That's slightly surprising as it's timing out with
the advertising code. (Which might suggest there's lock contention going
on somwhere).

I've considerably reworked the discovery loop. Can you pull and give it
another try, please?

**Comment by tomviner** [comment]
Tried again:
```
=========================================================== 27 passed in 6.58 seconds ============================================================
____________________________________________________________________ summary _____________________________________________________________________
  py27: commands succeeded
ERROR:   py33: InterpreterNotFound: python3.3
  py34: commands succeeded
  py35: commands succeeded
```

Nice work @tjguk !
