### ISSUE TITLE
Network interface binding

### ISSUE THREAD

**Issue by geokala** [tjguk/networkzero#34]
Out of interest (and maybe you already ran into a problem that prevented this), why don't you bind to either 0.0.0.0 (all interfaces, IPv4) or even to :: (all interfaces, IPv6 and IPv4 except for some advanced users... though this might not work on Windows?)?

That would remove a lot of the complexity of trying to find an interface and allow you to let people specify specific IPs (without wildcards) if they desired.

**Comment by tjguk** [comment]
Most of the business of finding an interface is so that you can advertise it to other people.

**Comment by tjguk** [comment]
Ok; I think I understand better what you're suggesting after our conversation last night. I *think* you're saying that the "address" (currently one string something like "192.168.1.10:12345") could actually be one IP:port for each network, with the correct one broadcast across the correct network.

in other words, if I have (handwaving the network details aside) 3 interfaces:

127.0.0.1
192.168.1.10
10.100.1.5

Then the "address" will in fact be a list of three IP:Port pairs, with the correct one used on each interface. Have I got that right?.

Assuming I have, then I think that this is *probably* overkill for what I need. At present, assuming nothing is specified, we're picking the default interface (thanks to your other patch) and then broadcasting that address across the broadcast address for each interface. This is workable but slightly clumsy; issue #42 is suggesting that the advert mechanism only broadcast addresses which are in the same network as the broadcast address.

Please feel free to comment / correct

**Comment by geokala** [comment]
Not quite.

So, you would first bind to 0.0.0.0:12345
This will make you listen on all (IPv4) addresses. You could probably bind to [::]:12345 (on most setups of Linux and probably on Macs and possibly on Windows (would need testing on those), this would bind you to all IPv4 and IPv6 addresses- maybe something to experiment with later).

In any case, this would mean you could dispense with the listening address as a configuration element.

Then, within the code, you need to make sure you are sending out your beacons correctly on each network. I don't recall exactly how your beacon (send and receipt) code works at the moment, so I will assume the receipt code uses the address the beacon it hears was sent from, rather than looking within the packet.
So, pseudocody:
```for interfaces in interfaces:
    if interface.ipv4 and not interface.is_loopback:
        beacon.send(interface.ipv4.broadcast_address)```
Using your example addresses (with arbitrary netmasks, and with loopback removed):
192.168.1.10/24 (broadcast: 192.168.1.255)
10.100.1.5/24 (broadcast: 10.100.1.255)

What will happen is that it will first try to send a beacon on 192.168.1.255. To do this, it will check the routing table, which will most likely (unless someone has really actively screwed things up on that machine) have the best route for 192.168.1.0/24 being on the interface with 192.168.1.10. So it should then send from that address.
Likewise, 10.100.1.5 should be used to send to 10.100.1.255.

If my assumption that the beacon receiver doesn't in fact use the source address, the above pseudocode would need modifying to actually put interface.ipv4.address into the beacon each time.

Hopefully that makes sense?
